### ISSUE TITLE
Problems with Artemis startup

### ISSUE THREAD

**Issue by BonusPlay** [CERT-Polska/Artemis#264]
These were also reported via discord, but I managed to replicate them on my setup. More info/logs will be posted here.
```
artemis-backend-1  | /usr/local/lib/python3.11/site-packages/karton/core/config.py:61: UserWarning: [minio] section in configuration is deprecated, replace it with [s3]
artemis-backend-1  |   warnings.warn(
artemis-backend-1  | Traceback (most recent call last):
artemis-backend-1  |   File "/usr/local/bin/uvicorn", line 8, in <module>
artemis-backend-1  |     sys.exit(main())
artemis-backend-1  |              ^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
artemis-backend-1  |     return self.main(*args, **kwargs)
artemis-backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
artemis-backend-1  |     rv = self.invoke(ctx)
artemis-backend-1  |          ^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
artemis-backend-1  |     return ctx.invoke(self.callback, **ctx.params)
artemis-backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
artemis-backend-1  |     return __callback(*args, **kwargs)
artemis-backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 403, in main
artemis-backend-1  |     run(
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 568, in run
artemis-backend-1  |     server.run()
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 59, in run
artemis-backend-1  |     return asyncio.run(self.serve(sockets=sockets))
artemis-backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
artemis-backend-1  |     return runner.run(main)
artemis-backend-1  |            ^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
artemis-backend-1  |     return self._loop.run_until_complete(task)
artemis-backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
artemis-backend-1  |     return future.result()
artemis-backend-1  |            ^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 66, in serve
artemis-backend-1  |     config.load()
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 471, in load
artemis-backend-1  |     self.loaded_app = import_from_string(self.app)
artemis-backend-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
artemis-backend-1  |     module = importlib.import_module(module_str)
artemis-backend-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
artemis-backend-1  |     return _bootstrap._gcd_import(name[level:], package, level)
artemis-backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
artemis-backend-1  |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
artemis-backend-1  |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
artemis-backend-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
artemis-backend-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
artemis-backend-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
artemis-backend-1  |   File "/opt/artemis/main.py", line 16, in <module>
artemis-backend-1  |     db.initialize_database()
artemis-backend-1  |   File "/opt/artemis/db.py", line 235, in initialize_database
artemis-backend-1  |     self.task_results.create_index(
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/pymongo/collection.py", line 2055, in create_index
artemis-backend-1  |     return self.__create_indexes([index], session, **cmd_options)[0]
artemis-backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
artemis-backend-1  |     return func(self, *args, **kwargs)
artemis-backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/pymongo/collection.py", line 1911, in __create_indexes
artemis-backend-1  |     with self._socket_for_writes(session) as sock_info:
artemis-backend-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/pymongo/collection.py", line 248, in _socket_for_writes
artemis-backend-1  |     return self.__database.client._socket_for_writes(session)
artemis-backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1267, in _socket_for_writes
artemis-backend-1  |     server = self._select_server(writable_server_selector, session)
artemis-backend-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1257, in _select_server
artemis-backend-1  |     server = topology.select_server(server_selector)
artemis-backend-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/pymongo/topology.py", line 272, in select_server
artemis-backend-1  |     server = self._select_server(selector, server_selection_timeout, address)
artemis-backend-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/pymongo/topology.py", line 261, in _select_server
artemis-backend-1  |     servers = self.select_servers(selector, server_selection_timeout, address)
artemis-backend-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/pymongo/topology.py", line 223, in select_servers
artemis-backend-1  |     server_descriptions = self._select_servers_loop(selector, server_timeout, address)
artemis-backend-1  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
artemis-backend-1  |   File "/usr/local/lib/python3.11/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
artemis-backend-1  |     raise ServerSelectionTimeoutError(
artemis-backend-1  | pymongo.errors.ServerSelectionTimeoutError: db:27017: [Errno -2] Name does not resolve, Timeout: 30s, Topology Description: <TopologyDescription id: 64171dc4adf6cec1ffeb07db, topology_type: Unknown, servers: [<ServerDescription ('db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('db:27017: [Errno -2] Name does not resolve')>]>
```

**Comment by BonusPlay** [comment]
Found the issue:
```
artemis-db-1  |
artemis-db-1  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
artemis-db-1  |   see https://jira.mongodb.org/browse/SERVER-54407
artemis-db-1  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
artemis-db-1  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
artemis-db-1  |
artemis-db-1  | /usr/local/bin/docker-entrypoint.sh: line 416:    26 Illegal instruction     "${mongodHackedArgs[@]}" --fork
```
